config/routes.rb
Rails.application.routes.draw do

  post 'polly/slash'
  get 'polly/auth', as: 'polly_auth'

  get 'caniuse/slash'

  get 'home/index'

  post 'frink/slash'
  get  'frink/auth', as: 'frink_auth'

  post 'morbo/slash'
  get  'morbo/auth', as: 'morbo_auth'

  post 'caniuse/slash'
  get  'caniuse/auth', as: 'caniuse_auth'

  post 'weather/slash'
  get  'weather/auth', as: 'weather_auth'

  post 'citibike/slash'
  get  'citibike/auth', as: 'citibike_auth'

  post 'cabi/slash' => 'capital_bikeshare#slash'
  get  'cabi/auth'  => 'capital_bikeshare#auth', as: 'cabi_auth'

  post 'beer/slash'
  get  'beer/auth', as: 'beer_auth'

  post 'metro/slash'
  get  'metro/auth', as: 'metro_auth'

  post 'link/slash'
  get  'link/auth', as: 'link_auth'

  post 'memefier/memefy'
  get  'memefier/memefy'
  post 'memefier/palette'
  post 'memefier/resize'
  get  'memefier/auth', as: 'memefier_auth'

  post 'custom/:action', controller: 'custom'

  root 'home#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    redirect_to "https://www.gesteves.com"
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/index.html.erb
<header class="header">
  <h1>Slack apps &amp; utilities</h1>
  <p>This is a small collection of Slack apps and slash commands I’ve put together over time.<br/>I hope you find some of them useful!</p>
  <p class="header__sign">&mdash;<a href="https://www.gesteves.com">G</a>.</p>
</header>

<div class="app">
<h2 id="frink">/frink <i>Simpsons gifs from <a href="https://frinkiac.com/">Frinkiac</a> in your Slack</i></h2>
  <%= image_tag 'frink.png', class: 'app__screenshot' %>
  <div class="app__button">
    <a class="button" href="https://slack.com/oauth/authorize?scope=commands&client_id=<%= ENV['FRINK_CLIENT_ID'] %>&amp;redirect_url=<%= frink_auth_url %>"><img alt="Add to Slack" height="40" width="139" src="https://platform.slack-edge.com/img/add_to_slack.png" srcset="https://platform.slack-edge.com/img/add_to_slack.png 1x, https://platform.slack-edge.com/img/add_to_slack@2x.png 2x"></a>
  </div>
</div>

<div class="app">
  <h2 id="morbo">/morbo <i>Futurama gifs from <a href="https://morbotron.com/">Morbotron</a> in your Slack</i></h2>
  <%= image_tag 'morbo.png', class: 'app__screenshot' %>
  <div class="app__button">
    <a class="button" href="https://slack.com/oauth/authorize?scope=commands&client_id=<%= ENV['MORBO_CLIENT_ID'] %>&amp;redirect_url=<%= morbo_auth_url %>"><img alt="Add to Slack" height="40" width="139" src="https://platform.slack-edge.com/img/add_to_slack.png" srcset="https://platform.slack-edge.com/img/add_to_slack.png 1x, https://platform.slack-edge.com/img/add_to_slack@2x.png 2x"></a>
  </div>
</div>

<div class="app">
  <h2 id="caniuse">/caniuse <i>Search <a href="http://caniuse.com/">caniuse.com</a> from Slack</i></h2>
  <%= image_tag 'caniuse.png', class: 'app__screenshot' %>
  <div class="app__button">
    <a class="button" href="https://slack.com/oauth/authorize?scope=commands&client_id=<%= ENV['CANIUSE_CLIENT_ID'] %>&amp;redirect_url=<%= caniuse_auth_url %>"><img alt="Add to Slack" height="40" width="139" src="https://platform.slack-edge.com/img/add_to_slack.png" srcset="https://platform.slack-edge.com/img/add_to_slack.png 1x, https://platform.slack-edge.com/img/add_to_slack@2x.png 2x"></a>
  </div>
</div>

<div class="app">
  <h2 id="weather">/weather <i>Up-to-the-minute weather forecasts from <a href="https://darksky.net">Dark Sky</a> in Slack</i></h2>
  <%= image_tag 'weather.png', class: 'app__screenshot' %>
  <div class="app__button">
    <a class="button" href="https://slack.com/oauth/authorize?scope=commands&client_id=<%= ENV['WEATHER_CLIENT_ID'] %>&amp;redirect_url=<%= weather_auth_url %>"><img alt="Add to Slack" height="40" width="139" src="https://platform.slack-edge.com/img/add_to_slack.png" srcset="https://platform.slack-edge.com/img/add_to_slack.png 1x, https://platform.slack-edge.com/img/add_to_slack@2x.png 2x"></a>
  </div>
</div>

<div class="app">
  <h2 id="metro">/metro <i>Arrival information for any Metro station in Washington, DC</i></h2>
  <%= image_tag 'metro.png', class: 'app__screenshot' %>
  <div class="app__button">
    <a class="button" href="https://slack.com/oauth/authorize?scope=commands&client_id=<%= ENV['METRO_CLIENT_ID'] %>&amp;redirect_url=<%= metro_auth_url %>"><img alt="Add to Slack" height="40" width="139" src="https://platform.slack-edge.com/img/add_to_slack.png" srcset="https://platform.slack-edge.com/img/add_to_slack.png 1x, https://platform.slack-edge.com/img/add_to_slack@2x.png 2x"></a>
  </div>
</div>

<div class="app">
  <h2 id="cabi">/cabi <i>Find <a href="https://www.capitalbikeshare.com/">Capital Bikeshare</a> stations in Washington, DC</i></h2>
  <%= image_tag 'cabi.png', class: 'app__screenshot' %>
  <div class="app__button">
    <a class="button" href="https://slack.com/oauth/authorize?scope=commands&client_id=<%= ENV['CABI_CLIENT_ID'] %>&amp;redirect_url=<%= cabi_auth_url %>"><img alt="Add to Slack" height="40" width="139" src="https://platform.slack-edge.com/img/add_to_slack.png" srcset="https://platform.slack-edge.com/img/add_to_slack.png 1x, https://platform.slack-edge.com/img/add_to_slack@2x.png 2x"></a>
  </div>
</div>

<div class="app">
  <h2 id="citibike">/citibike <i>Find <a href="https://www.citibikenyc.com/">Citibike</a> stations in New York City</i></h2>
  <%= image_tag 'citibike.png', class: 'app__screenshot' %>
  <div class="app__button">
    <a class="button" href="https://slack.com/oauth/authorize?scope=commands&client_id=<%= ENV['CITIBIKE_CLIENT_ID'] %>&amp;redirect_url=<%= citibike_auth_url %>"><img alt="Add to Slack" height="40" width="139" src="https://platform.slack-edge.com/img/add_to_slack.png" srcset="https://platform.slack-edge.com/img/add_to_slack.png 1x, https://platform.slack-edge.com/img/add_to_slack@2x.png 2x"></a>
  </div>
</div>

<div class="app">
  <h2 id="link">/linkhere <i>Generate links to any channel or DM so you can use them in email and documents</i></h2>
  <%= image_tag 'link.png', class: 'app__screenshot' %>
  <div class="app__button">
    <a class="button" href="https://slack.com/oauth/authorize?scope=commands&client_id=<%= ENV['LINK_CLIENT_ID'] %>&amp;redirect_url=<%= link_auth_url %>"><img alt="Add to Slack" height="40" width="139" src="https://platform.slack-edge.com/img/add_to_slack.png" srcset="https://platform.slack-edge.com/img/add_to_slack.png 1x, https://platform.slack-edge.com/img/add_to_slack@2x.png 2x"></a>
  </div>
</div>

<div class="app__button" style="display:none">
  <a class="button" href="https://slack.com/oauth/authorize?scope=commands&client_id=<%= ENV['POLLY_CLIENT_ID'] %>&amp;redirect_url=<%= polly_auth_url %>"><img alt="Add to Slack" height="40" width="139" src="https://platform.slack-edge.com/img/add_to_slack.png" srcset="https://platform.slack-edge.com/img/add_to_slack.png 1x, https://platform.slack-edge.com/img/add_to_slack@2x.png 2x"></a>
</div>